### ISSUE TITLE
404 Not Found: http://jshint.com/platforms/#editors

### ISSUE THREAD

**Issue by Krinkle** [jshint/jshint.github.io#10]
The url http://jshint.com/platforms/#editors used to work. I suppose the replacement page is http://jshint.com/install/ (though without a section anchor for the editor plugins section).

I've updated links where I could find, but a redirect would be nice. Cool URIs don't break :)

**Comment by jugglinmike** [comment]
Thanks for the report! I've only recently inherited the website, so bear with me while I figure this out.

I can't find any indication of a "platforms" page in the project history. Since the site is (and always has been?) statically generated, I would expect a file to show up somewhere, but no:

    $ git log --stat | grep -i platform
    $

Also searching for the string in all the diffs (via `git log -Splatforms`) only returns blog post content (not links).

@valueof I'm wondering if you set up a URL redirect on your server before we moved to GitHub pages? I know this is a tiny detail, but I thought I'd ask just in case

**Comment by jugglinmike** [comment]
Actually, the WayBack machine is super helpful here: https://web.archive.org/web/20130501000000*/http://jshint.com/platforms

@Krinkle I'll get right on this!

@valueof Looks like we're good; sorry for the noise!

**Comment by jugglinmike** [comment]
Okay I've set up a basic redirect for the `/platforms` page: http://jshint.com/platforms/ . There's still no IDs in use on `/install`, but I'm less inclined to get that working again--it looks like we'd need a new Markdown parser and extra JavaScript to preserve URL parts across redirects.

@Krinkle if you could confirm (and agree that TBL probably didn't mean "Cool fragment identifiers don't change"), then I'd like to close this issue.

**Comment by Krinkle** [comment]
@jugglinmike Thanks!

As for "Cool fragment identifiers don't change", the web isn't built with that in mind unfortunately. I did some clean up work in a project recently. Lots of comments referencing w3 specs. It linked dev branches on w3.org (instead of permalinks or stable versions). Many of the anchors no longer resolved. They're typically very long pages; which had been completely rewritten since. It would be "cool" for the web to have a more accessible and standardised structure for individual pieces of information. Data that can be flexibly referenced. Site authors can still re-arrange data and phrasing over time but references to specific data would always result in a redirect to a page where that data is shown in context with other data. One day :)
