### ISSUE TITLE
Broken/redirecting link on about page

### ISSUE THREAD

**Issue by roboffer** [jshint/jshint.github.io#44]
The link to Pandoo TEK one the [about page](http://jshint.com/about/) seems to act strangely, redirecting a few times and takes you to a suspect site.

If you need a replacement URL we are starting to use JSHint and would be happy to be listed.

**Comment by jugglinmike** [comment]
Today, the link appears to be simply broken. Given that it's been a "coming soon" page for the past year, I think it's time we remove it altogether. Likewise, `odesk.com` appears to have changed hands, so that ought to go, too.

This information is maintained in the main project's `README.md` file and re-published on the website. The change is now in `master` (see https://github.com/jshint/jshint/commit/3435d186ef63641af65b1c89cd64d8642ce978ea), and it will propagate to the web site the next time we deploy.

Thanks for the report!
